### ISSUE TITLE
Include links to changes in output

### ISSUE THREAD

**Issue by elazar** [deprecat/climb#24]
For each dependency with an available upgrade, it would be very helpful if the console output could provide a direct link to either a relevant `CHANGELOG` file where available and/or a link to a GitHub diff between the current and available versions.

This would make it easier to gauge the chance of an upgrade breaking usage in a project for projects that don't strictly practice semver.

I realize this feature would be non-trivial to implement, and perhaps would be better placed in a separate utility, but I think integration with this utility could be very useful.

**Comment by jbrooksuk** [comment]
The issue I see here is that `CHANGELOG` files are generally very unstandardised.

**Comment by vinkla** [comment]
I do like the idea but I think @jbrooksuk's point is valid. This would be very hard to implement. Maybe we could just provide a link to the releases page on GitHub?

**Comment by elazar** [comment]
I think the bigger value would be in seeing the specific changes. Linking to those given the original version tags is easy enough to do, e.g. https://github.com/relayphp/Relay.Relay/compare/1.x...2.x

**Comment by juliangut** [comment]
You are presenting two different things here, chanchelogs which are developer managed and are indeed very different from one another, on the other side a git diff would only be useful if the releases are not that far from each other because the list of commits and line changes would be unmanageables.

Having a changelog PSR would be nice yo achieve this goal

**Comment by vinkla** [comment]
We should also discuss how it would work. Are you suggestion we put the links within the output?

Maybe we could add a command to include them e.g. `climb --with-links` or something similar.

**Comment by elazar** [comment]
Yes, I'm suggesting links within the output, and see no issue with them only showing up if an optional flag is specified.

**Comment by vinkla** [comment]
Sounds good. Would be awesome if you wanted to create a PR for this.

**Comment by mikemand** [comment]
Maybe some way to integrate with [pyrech/composer-changelogs](https://github.com/pyrech/composer-changelogs)?

**Comment by vinkla** [comment]
@mikemand Thanks, great suggestion :+1:

**Comment by vinkla** [comment]
Thanks but I've deprecated this package now since it is [added to to Composer](https://medium.com/@vinkla/find-outdated-packages-with-composer-968828c1d80a) out of the box.
