### ISSUE TITLE
Satis Support (alternative packagist URL)

### ISSUE THREAD

**Issue by Method-es** [deprecat/climb#26]
Hi; I started using this today and I found it worked very well when I was working on some of our internal projects. However; I tried then upgrading a client site using our internal packages (on our Satis server), and I noticed climb would always tell me everything was up to date. 

I don't currently have time today to work on a PR or anything, but my initial investigation would indicate that you would need access to the composer.json file as well as the .lock; as the external repos are not stored in the .lock file;

in addition it appears the Packagist API that is being used (Packagist\API\Client) is using default params, but appears to support a URL param.

The complicated bit will be into how to collate the responses together... and respecting the HTTP auth capabilities... This could be a big deal for how much work is involved, but I think irrelevant of the chosen approach; without this feature I don't think I can trust this package (yet), as I would have to manually double check all the self-hosted projects/packages.

**Comment by vinkla** [comment]
This could be a nice feature. I'm not sure about the implementation but if the urls exists within the `composer.lock` file this might be possible to solve. I'll keep this issue here as a reminder.

**Comment by adambiggs** [comment]
This would be a really great addition. I noticed climb doesn't seem to work with [WordPress Packagist](https://wpackagist.org).

**Comment by vinkla** [comment]
Thanks but I've deprecated this package now since it is [added to to Composer](https://medium.com/@vinkla/find-outdated-packages-with-composer-968828c1d80a) out of the box.

**Comment by vinkla** [comment]
@adambiggs Composer's outdated command works with wpackagist.
