### ISSUE TITLE
Exclude Unstable Versions

### ISSUE THREAD

**Issue by vinkla** [deprecat/climb#36]
We need to exclude unstable version when running `outdated` and `update`. Better would be to add a flag if we want to include them. Something like `climb update --unstable`.

**Comment by vinkla** [comment]
We could also allow to send `--alpha`, `--beta`, `--rc` and `--dev` to include specific stabilities.

**Comment by bocharsky-bw** [comment]
:+1:

**Comment by vinkla** [comment]
Thanks but I've deprecated this package now since it is [added to to Composer](https://medium.com/@vinkla/find-outdated-packages-with-composer-968828c1d80a) out of the box.
