### ISSUE TITLE
Filter major/minor updates

### ISSUE THREAD

**Issue by mbrodala** [deprecat/climb#52]
Right now climb already shows major and minor updates in separate sections. It would be useful if there where CLI flags like `--major` and `--minor` / `--no-major` to only show one of the two sections.

Background: major updates are rare and periodically checking for minor updates could be a useful CI addition.

**Comment by vinkla** [comment]
We already have added this in #42.

**Comment by vinkla** [comment]
I do like your flag names though.

**Comment by mbrodala** [comment]
Good idea. From what I can see `--exclude` only allows me to exclude a list of known package names which isnt't exactly what I mean. But I think you already got what I mean. ;-)

**Comment by vinkla** [comment]
I'm referring to the `--outdated` and `--upgradable` flags

**Comment by vinkla** [comment]
Thanks but I've deprecated this package now since it is [added to to Composer](https://medium.com/@vinkla/find-outdated-packages-with-composer-968828c1d80a) out of the box.
