### ISSUE TITLE
Exclude incompatible updates

### ISSUE THREAD

**Issue by mbrodala** [deprecat/climb#53]
Currently `climb` lists the newest available release as potential update.

However, some updates may not be compatible with other currently installed packages.

Example:

* Installed: `typo3/cms` 6.2.17
* Installed: [`helhum/typo3-console` 1.1.6](https://packagist.org/packages/helhum/typo3-console#1.1.6), for `typo3/cms` >=6.2.6,<7.3.0
* Suggested: [`helhum/typo3-console` 1.2.5](https://packagist.org/packages/helhum/typo3-console#1.2.5), for  `typo3/cms` >=7.4.0,<8.0

As you can see, the suggested update is actually not installable and thus should not be shown (or hidden behind a flag.)

**Comment by mbrodala** [comment]
Another example:

```
$ climb

...
phpunit/phpunit          4.8.3      →     5.2.3
```

This ignores the fact that PHPUnit 5.x depends on PHP 5.6/7.x and PHP 5.5 is installed here.

**Comment by vinkla** [comment]
I understand your point. Maybe we should add a flag to only compare against non-breaking version. If you feel up for it it would be awesome if you could create a pull request for this!

**Comment by mbrodala** [comment]
This is quite hard to fix since one has to basically reimplement `composer update --dry-run` which requires a lot more logic than the current simple version comparison.

**Comment by vinkla** [comment]
Thanks but I've deprecated this package now since it is [added to to Composer](https://medium.com/@vinkla/find-outdated-packages-with-composer-968828c1d80a) out of the box.
